import { Navbar } from "@/components/Navbar";
import Head from "next/head";
import React from "react";
import { Box, Button, Tooltip, VStack } from "@chakra-ui/react";
import {
  LinkInBioIcon,
  StoreIcon,
  MediaKitIcon,
  InvoicingIcon,
} from "@/components/Icon";

type Props = {
  children: React.ReactNode;
};

export default function Layout({ children }: Props) {
  const floatingNavItems = [
    {
      name: "Link in bio",
      icon: <LinkInBioIcon />,
    },
    {
      name: "Store",
      icon: <StoreIcon />,
    },
    {
      name: "Media Kit",
      icon: <MediaKitIcon />,
    },
    {
      name: "Invoicing",
      icon: <InvoicingIcon />,
    },
  ];
  return (
    <>
      <Head>
        <title>Mainstack assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box background={"#ffffff"} padding="0 16px">
        <Navbar />
        <Box padding={"64px 140px"} maxW="1460px" margin="0 auto" w="100%">
          <VStack
            gap="15px"
            position={"fixed"}
            top="35%"
            left="16px"
            w={"48px"}
            backgroundColor="white"
            borderRadius={"100px"}
            boxShadow={
              "0px 4px 8px 0px rgba(92, 115, 131, 0.08), 0px 2px 6px 0px rgba(92, 115, 131, 0.08)"
            }
            paddingY="10px"
          >
            {floatingNavItems.map((item, index) => (
              <Tooltip
                hasArrow
                key={index}
                placement={"end"}
                label={item.name}
                padding="10px"
                borderRadius={10}
              >
                <Button
                  bg="transparent"
                  borderRadius={"full"}
                  height={"40px"}
                  width={"40px"}
                  _hover={{ bg: "brand.gray50", filter: "grayscale(0)" }}
                  filter={"grayscale(1)"}
                >
                  <Box>{item.icon}</Box>
                </Button>
              </Tooltip>
            ))}
          </VStack>
          {children}
        </Box>
      </Box>
    </>
  );
}
